language: python
python:
  - 2.7
before_install:
  - time pip install -r requirements/testing.txt

script:
  - pep8 hotsparser
  - pylint hotsparser
  - flake8 hotsparser

sudo: false

notifications:
  email:
    on_success: never
    on_failure: never